[programs.devnet]
myepicproject = "Cq1TSA1obVQZzw2YYxvFN6Q5ia5TYxSbwyZQ9JwQCbBL"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/jobymacbookpro/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"
